### ISSUE TITLE
Adafruit_MCP23017.h file missing

### ISSUE THREAD

**Issue by was-euraquilo** [ZioGuido/GMLAB_D9X#2]
The sketch for GMLAB_D9X has an include line for Adafruit_MCP23017.h but the only file that comes close to this in the Adafruit library is one called Adafruit_MCP23X17.h.  Should I just manually modify the sketch to Adafruit_MCP23X17.h?

**Comment by ZioGuido** [comment]
In the library browser of the Arduino IDE search for MCP23017 and install the Adafruit library. If it doesn't work yet, they must have introduced some breaking change in one of their latest updates, so you could try to install an older version of the library and retry compiling. Or you could adapt this sketch to the latest changes of the Adafruit library.

**Comment by ZioGuido** [comment]
Well yes, considering this sketch was posted 4 years ago, there's a likeliness that they've changed something in the Adafruit libraries. Now if you don't need to use any of the new changes, the easiest solution is to install an older version that still had the working file. Unfortunately I can't tell which version number it was.

**Comment by was-euraquilo** [comment]
I did install the Adafruit library, and that's when I found there was no Adafruit_MCP23017.h, but instead there was an Adafruit_MCP23X17.h. 
I'm pretty new to this, so I don't know where I can find an older version of that library.

**Comment by ZioGuido** [comment]
The library manager of the Arduino IDE lets you choose which version of a library you wish to install.

**Comment by was-euraquilo** [comment]
Ah yes. thank you.

**Comment by nathan-stewart** [comment]
You need Adafruit MCP23017 v1.0.6 or earlier
