### ISSUE TITLE
How can I reverse the Drawbars?

### ISSUE THREAD

**Issue by musicmikemusic** [ZioGuido/GMLAB_D9X#6]
Hi there,

I LOVE the D9X! I use it with MainStage from Apple. 
But: The Drawbars are inverted in MainStage. I would be great if I could program the drawbars inverted. Fully pulled 0 and retracted 127. How can I achieve that? I have no clue of programing that thing ;-)

greetings 
Mike

**Comment by biensz** [comment]
hi mike,

great to hear you're enjoying the D9X! to invert the drawbars in mainstage, you can make a simple modification to the arduino code. follow these steps:

1. download arduino.ide:
if you haven't already, download and install the arduino.ide

2. open the code:
launch arduino.ide, open the d9x midi controller code, and ensure your arduino board is connected.

3. locate the drawbar control section:
in the code, find the section responsible for sending midi messages for the drawbars. it should look like this:
`sendmidicc(0, drawbarccmap[drawbar_set][d - 7], val7bit);`

4. modify the line / change to:
`sendmidicc(0, drawbarccmap[drawbar_set][d - 7], 127 - val7bit);`

5. upload the code:
click "upload" to update the code on your D9X midi controller.

why this change:
the modification uses 127 as the maximum midi value. by subtracting the current value from 127, it effectively inverts the drawbars, making fully pulled equal to 0 and fully retracted equal to 127.

now, when you use the drawbars, they should be inverted in mainstage. feel free to reach out if you have any questions!

cheers,
biens

p.s.: ensure that the required libraries from the original code (including MIDIUSB, MIDI, EEPROM, WIRE, MILLISTIMER) are also installed. you can directly fetch them using the library manager.
for the adafruit I/O, i used version 1.0.6 to adapt it to the existing code. you can install it directly through the IDE or [here](https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/tree/1.0.6/).

**Comment by musicmikemusic** [comment]
WOW! That did the trick! Absolutely awesome biensz!!!
